sudo: required
dist: trusty
language: c

# Pre-install missing build dependencies:
# - valgrind (from the repo)
# - libcheck 0.9.10 is slightly too old, since 0.9.12 adds TAP support
before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y valgrind

install:
        - wget http://downloads.sourceforge.net/project/check/check/0.10.0/check-0.10.0.tar.gz
        - tar -xvf check-0.10.0.tar.gz
        - pushd check-0.10.0 && ./configure --prefix=/usr && make -j48 && sudo make install && popd

# Ubuntu's default umask is 0002, but tests are written with the expectation of a 0022 default.
script:
        - autoreconf --verbose --warnings=none --install --force && ./configure && make -j48 && sudo sh -c 'umask 0022 && make -j48 check'
after_failure: cat test-suite.log
